export const sessionCategories = Object.freeze({
  REGULAR: 'Regular',
  EVENT: 'Event',
});

export const subjectTypes = Object.freeze({
  PLANET: 'Planet',
  MOON: 'Moon',
  SUN: 'Sun',
  SATELLITE: 'Satellite',
  COMET: 'Comet',
  GALAXY: 'Galaxy',
  NEBULA: 'Nebula',
  OPEN_STAR_CLUSTER: 'Open Star Cluster',
  GLOBULAR_STAR_CLUSTER: 'Globular Star Cluster',
});

export const telescopeTypes = Object.freeze({
  REFLECTOR: 'Reflector',
  REFRACTOR: 'Refractor',
  CASSEGRAIN: 'Cassegrain',
});

export const eyepieceOpticalSchemas = Object.freeze({
  KELLNER: 'Kellner',
  PLOSSL: 'Plossl',
  ERFLE: 'Erfle',
  XWA: 'Extra Wide Angle',
});

export const eyepieceSizeSchemas = Object.freeze({
  SMALL: `1.25''`,
  BIG: `2''`,
});

export const barlowLensSchemas = Object.freeze({
  DOUBLE: '2X',
  TRIPPLE: '3X',
});

export const filterTypes = Object.freeze({
  NEBULA: 'Nebula',
  PLANETARY: 'Planetary',
  ASTROPHOTOGRAPHY: 'Astrophotography',
  SOLAR: 'Solar',
});

export const seeds = {
  users: {
    data: [
      {
        fistName: 'Toma',
        lastName: 'Kachinsky',
        email: 'toma.kashinsky93@gmail.com',
        password: 'Abcde$12345',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        fistName: 'Luke',
        lastName: 'Johnson',
        email: 'teo.r3@hotmail.com',
        password: 'Ade_12345cD',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        fistName: 'Marek',
        lastName: 'Blashchinsky',
        email: 'speedy-5D.test@gmail.com',
        password: 'A8_345dBe1q',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
    associations: {
      tokens: {
        data: [
          {
            userId: 1,
            refreshToken:
              'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eymaWNhdGlvbkxpbmsiOiIiLCJpZCI6JkYXRhVmFsdWVzIjp7ImlzVmVyaWZpZWQiOjAsInZlcmlMywidXNlcm5hbWUiOiJucGFuY2gyOTg5IiwiZW1haWwiOiJuYXphci5wYW5jaGVua29AaW5jb2RlLWl0LmNvbSIsInBhc3N3b3JkIjoiJDJiJDE1JGpKV0JpQ3FHek5leTJteERZT2FHVXVCbERta0VRT0VPYU1HMUJQWFNRVTBQQklJMXpWYks2IiwidXBkYXRlZEF0IjoiMjAyMy0wMy0xM1QyMjowODozNC44OTZaIiwiY3JlYXRlZEF0IjoiMjAyMy0wMy0xM1QyMjowODozNC44OTZaIn0sIl9wcmV2aW91c0RhdGFWYWx1ZXMiOnsidXNlcm5hbWUiOiJucGFuY2gyOTg5IiwiZW1haWwiOiJuYXphci5wYW5jaGVua29AaW5jb2RlLWl0LmNvbSIsInBhc3N3b3JkIjoiJDJiJDE1JGpKV0JpQ3FHek5leTJteERZT2FHVXVCbERta0VRT0VPYU1HMUJQWFNRVTBQQklJMXpWYks2IiwiaWQiOjMsImlzVmVyaWZpZWQiOjAsInZlcmlmaWNhdGlvbkxpbmsiOiIiLCJjcmVhdGVkQXQiOiIyMDIzLTAzLTEzVDIyOjA4OjM0Ljg5NloiLCJ1cGRhdGVkQXQiOiIyMDIzLTAzLTEzVDIyOjA4OjM0Ljg5NloifSwidW5pcW5vIjoxLCJfY2hhbmdlZCI6e30sIl9vcHRpb25zIjp7ImlzTmV3UmVjb3JkIjp0cnVlLCJfc2NoZW1hIjpudWxsLCJfc2NoZW1hRGVsaW1pdGVyIjoiIn0sImlzTmV3UmVjb3JkIjpmYWxzZSwiaWF0IjoxNjc4NzQ1MzE3LCJleHAiOjE2Nzg3NDU2Nzd9.JU5iGC7nrKno2lF5ueCiho350W7NQ7zD6yzuQT8pEwM',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            userId: 2,
            refreshToken:
              '9JCVXPKi6cInIsI1ZUJiOgcHbaYe.eyJpZCI6MywidXNlcm5hbWkYXRhVmFsdWVzIjp7ImlzVmVyaWZpZWQiOjAsInZlcmlmaWNhdGlvbkxpbmsiOiIiLCJUiOiJucGFuY2gyOTg5IiwiZW1haWwiOiJuYXphci5wYW5jaGVua29AaW5jb2RlLWl0LmNvbSIsInBhc3N3b3JkIjoiJDJiJDE1JGpKV0JpQ3FHek5leTJteERZT2FHVXVCbERta0VRT0VPYU1HMUJQWFNRVTBQQklJMXpWYks2IiwidXBkYXRlZEF0IjoiMjAyMy0wMy0xM1QyMjowODozNC44OTZaIiwiY3JlYXRlZEF0IjoiMjAyMy0wMy0xM1QyMjowODozNC44OTZaIn0sIl9wcmV2aW91c0RhdGFWYWx1ZXMiOnsidXNlcm5hbWUiOiJucGFuY2gyOTg5IiwiZW1haWwiOiJuYXphci5wYW5jaGVua29AaW5jb2RlLWl0LmNvbSIsInBhc3N3b3JkIjoiJDJiJDE1JGpKV0JpQ3FHek5leTJteERZT2FHVXVCbERta0VRT0VPYU1HMUJQWFNRVTBQQklJMXpWYks2IiwiaWQiOjMsImlzVmVyaWZpZWQiOjAsInZlcmlmaWNhdGlvbkxpbmsiOiIiLCJjcmVhdGVkQXQiOiIyMDIzLTAzLTEzVDIyOjA4OjM0Ljg5NloiLCJ1cGRhdGVkQXQiOiIyMDIzLTAzLTEzVDIyOjA4OjM0Ljg5NloifSwidW5pcW5vIjoxLCJfY2hhbmdlZCI6e30sIl9vcHRpb25zIjp7ImlzTmV3UmVjb3JkIjp0cnVlLCJfc2NoZW1hIjpudWxsLCJfc2NoZW1hRGVsaW1pdGVyIjoiIn0sImlzTmV3UmVjb3JkIjpmYWxzZSwiaWF0IjoxNjc4NzQ1MzE3LCJleHAiOjE2Nzg3NDU2Nzd9.JU5iGC7nrKno2lF5ueCiho350W7NQ7zD6yzuQT8pEwM',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            userId: 3,
            refreshToken:
              'IsInR5cCI6IkpXVCJ9eyJhbGciOiJIUzI1Ni.eyJkYXRhVmFsdWVzIjp7ImlzVmVyaWZpZWQiOjAsInZlcmlmaWNhdGlvbkxpbmsiOiIiLCJpZCI6MywidXNlcm5hbWUiOiJucGFuY2gyOTg5IiwiZW1haWwiOiJuYXphci5wYW5jaGVua29AaW5jb2RlLWl0LmNvbSIsInBhc3N3b3JkIjoiJDJiJDE1JGpKV0JpQ3FHek5leTJteERZT2FHVXVCbERta0VRT0VPYU1HMUJQWFNRVTBQQklJMXpWYks2IiwidXBkYXRlZEF0IjoiMjAyMy0wMy0xM1QyMjowODozNC44OTZaIiwiY3JlYXRlZEF0IjoiMjAyMy0wMy0xM1QyMjowODozNC44OTZaIn0sIl9wcmV2aW91c0RhdGFWYWx1ZXMiOnsidXNlcm5hbWUiOiJucGFuY2gyOTg5IiwiZW1haWwiOiJuYXphci5wYW5jaGVua29AaW5jb2RlLWl0LmNvbSIsInBhc3N3b3JkIjoiJDJiJDE1JGpKV0JpQ3FHek5leTJteERZT2FHVXVCbERta0VRT0VPYU1HMUJQWFNRVTBQQklJMXpWYks2IiwiaWQiOjMsImlzVmVyaWZpZWQiOjAsInZlcmlmaWNhdGlvbkxpbmsiOiIiLCJjcmVhdGVkQXQiOiIyMDIzLTAzLTEzVDIyOjA4OjM0Ljg5NloiLCJ1cGRhdGVkQXQiOiIyMDIzLTAzLTEzVDIyOjA4OjM0Ljg5NloifSwidW5pcW5vIjoxLCJfY2hhbmdlZCI6e30sIl9vcHRpb25zIjp7ImlzTmV3UmVjb3JkIjp0cnVlLCJfc2NoZW1hIjpudWxsLCJfc2NoZW1hRGVsaW1pdGVyIjoiIn0sImlzTmV3UmVjb3JkIjpmYWxzZSwiaWF0IjoxNjc4NzQ1MzE3LCJleHAiOjE2Nzg3NDU2Nzd9.JU5iGC7nrKno2lF5ueCiho350W7NQ7zD6yzuQT8pEwM',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
        ],
        associations: {
          sessions: {
            data: [
              {
                sessionId: 1,
                subject: 'Moon',
                telescopeType: telescopeTypes.REFLECTOR,
                magnification: '83X',
                observationRealDurationMin: 25,
                observationVirtualDurationMin: 25,
                observationStartDate: new Date('2022-02-12T23:24:00Z'),
                observationEndDate: new Date('2022-02-12T23:49:00Z'),
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString(),
              },
              {
                sessionId: 8,
                subject: 'Jupiter',
                telescopeType: telescopeTypes.REFLECTOR,
                magnification: '139X',
                observationRealDurationMin: 74,
                observationVirtualDurationMin: 74,
                observationStartDate: new Date('2022-03-09T17:49:00Z'),
                observationEndDate: new Date('2022-03-09T19:03:00Z'),
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString(),
              },
              {
                sessionId: 8,
                subject: 'Saturn',
                telescopeType: telescopeTypes.REFLECTOR,
                magnification: '198',
                observationRealDurationMin: 48,
                observationVirtualDurationMin: 48,
                observationStartDate: new Date('2022-03-09T19:10:00Z'),
                observationEndDate: new Date('2022-03-09T19:58:00Z'),
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString(),
              },
              {
                sessionId: 1,
                subject: 'Moon',
                telescopeType: telescopeTypes.REFLECTOR,
                magnification: '250X',
                observationRealDurationMin: 77,
                observationVirtualDurationMin: 73,
                observationStartDate: new Date('2022-02-12T23:53:00Z'),
                observationEndDate: new Date('2022-03-13T01:06:00Z'),
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString(),
              },
              {
                sessionId: 1,
                subject: 'M44',
                telescopeType: telescopeTypes.REFLECTOR,
                magnification: '41X',
                observationRealDurationMin: 51,
                observationVirtualDurationMin: 51,
                observationStartDate: new Date('2022-03-12T01:12:00Z'),
                observationEndDate: new Date('2022-03-12T02:01:00Z'),
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString(),
              },
              {
                sessionId: 5,
                subject: 'Saturn',
                telescopeType: telescopeTypes.CASSEGRAIN,
                magnification: '220X',
                observationRealDurationMin: 27,
                observationVirtualDurationMin: 27,
                observationStartDate: new Date('2022-03-01T17:41:00Z'),
                observationEndDate: new Date('2022-03-01T18:08:00Z'),
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString(),
              },
              {
                sessionId: 8,
                subject: 'M44',
                telescopeType: telescopeTypes.REFLECTOR,
                magnification: '139X',
                observationRealDurationMin: 33,
                observationVirtualDurationMin: 31,
                observationStartDate: new Date('2022-03-02T21:18:00Z'),
                observationEndDate: new Date('2022-03-02T21:51:00Z'),
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString(),
              },
              {
                sessionId: 9,
                subject: 'Moon',
                telescopeType: telescopeTypes.REFLECTOR,
                magnification: '312X',
                observationRealDurationMin: 120,
                observationVirtualDurationMin: 120,
                observationStartDate: new Date('2022-03-03T23:00:00Z'),
                observationEndDate: new Date('2022-03-04T01:00:00Z'),
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString(),
              },
              {
                sessionId: 8,
                subject: 'M44',
                telescopeType: telescopeTypes.REFLECTOR,
                magnification: '41X',
                observationRealDurationMin: 31,
                observationVirtualDurationMin: 31,
                observationStartDate: new Date('2022-03-02T21:52:00Z'),
                observationEndDate: new Date('2022-03-02T22:23:00Z'),
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString(),
              },
              {
                sessionId: 5,
                subject: 'Saturn',
                telescopeType: telescopeTypes.CASSEGRAIN,
                magnification: '160X',
                observationRealDurationMin: 47,
                observationVirtualDurationMin: 39,
                observationStartDate: new Date('2022-03-01T18:11:00Z'),
                observationEndDate: new Date('2022-03-01T18:58:00Z'),
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString(),
              },
              {
                sessionId: 3,
                subject: 'M42',
                telescopeType: telescopeTypes.REFLECTOR,
                magnification: '225X',
                observationRealDurationMin: 80,
                observationVirtualDurationMin: 69,
                observationStartDate: new Date('2022-02-16T20:00:00Z'),
                observationEndDate: new Date('2022-02-16T21:20:00Z'),
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString(),
              },
              {
                sessionId: 9,
                subject: 'M44',
                telescopeType: telescopeTypes.CASSEGRAIN,
                magnification: '41X',
                observationRealDurationMin: 45,
                observationVirtualDurationMin: 43,
                observationStartDate: new Date('2022-03-12T17:59:00Z'),
                observationEndDate: new Date('2022-03-12T18:44:00Z'),
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString(),
              },
              {
                sessionId: 9,
                subject: 'Saturn',
                telescopeType: telescopeTypes.CASSEGRAIN,
                magnification: '280X',
                observationRealDurationMin: 90,
                observationVirtualDurationMin: 90,
                observationStartDate: new Date('2022-03-12T22:00:00Z'),
                observationEndDate: new Date('2022-03-12T23:30:00Z'),
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString(),
              },
              {
                sessionId: 9,
                subject: 'M51',
                telescopeType: telescopeTypes.CASSEGRAIN,
                magnification: '143X',
                observationRealDurationMin: 120,
                observationVirtualDurationMin: 120,
                observationStartDate: new Date('2022-03-12T01:00:00Z'),
                observationEndDate: new Date('2022-03-12T02:30:00Z'),
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString(),
              },
              {
                sessionId: 9,
                subject: 'NGC 457',
                telescopeType: telescopeTypes.REFLECTOR,
                magnification: '41X',
                observationRealDurationMin: 13,
                observationVirtualDurationMin: 13,
                observationStartDate: new Date('2022-03-12T17:36:00Z'),
                observationEndDate: new Date('2022-03-12T17:49:00Z'),
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString(),
              },
              {
                sessionId: 2,
                subject: 'Giades Open Cluster',
                telescopeType: telescopeTypes.REFLECTOR,
                magnification: '41X',
                observationRealDurationMin: 37,
                observationVirtualDurationMin: 37,
                observationStartDate: new Date('2022-02-15T04:02:00Z'),
                observationEndDate: new Date('2022-02-15T04:39:00Z'),
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString(),
              },
              {
                sessionId: 2,
                subject: 'M42',
                telescopeType: telescopeTypes.REFLECTOR,
                magnification: '83X',
                observationRealDurationMin: 32,
                observationVirtualDurationMin: 32,
                observationStartDate: new Date('2022-02-15T00:09:00Z'),
                observationEndDate: new Date('2022-02-15T00:41:00Z'),
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString(),
              },
              {
                sessionId: 4,
                subject: 'Caldwell 14',
                telescopeType: telescopeTypes.REFLECTOR,
                magnification: '83X',
                observationRealDurationMin: 180,
                observationVirtualDurationMin: 180,
                observationStartDate: new Date('2022-12-23T02:00:00Z'),
                observationEndDate: new Date('2022-12-23T05:00:00Z'),
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString(),
              },
              {
                sessionId: 2,
                subject: 'Giades Open Cluster',
                telescopeType: telescopeTypes.REFLECTOR,
                magnification: '83X',
                observationRealDurationMin: 63,
                observationVirtualDurationMin: 54,
                observationStartDate: new Date('2022-02-18T01:58:00Z'),
                observationEndDate: new Date('2022-02-18T03:01:00Z'),
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString(),
              },
              {
                sessionId: 9,
                subject: 'Caldwell 14',
                telescopeType: telescopeTypes.CASSEGRAIN,
                magnification: '41X',
                observationRealDurationMin: 28,
                observationVirtualDurationMin: 28,
                observationStartDate: new Date('2022-03-12T05:14:00Z'),
                observationEndDate: new Date('2022-03-12T05:42:00Z'),
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString(),
              },
              {
                sessionId: 2,
                subject: 'Caldwell 14',
                telescopeType: telescopeTypes.REFLECTOR,
                magnification: '41X',
                observationRealDurationMin: 34,
                observationVirtualDurationMin: 33,
                observationStartDate: new Date('2022-02-18T03:04:00Z'),
                observationEndDate: new Date('2022-02-18T03:38:00Z'),
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString(),
              },
              {
                sessionId: 6,
                subject: 'M33',
                telescopeType: telescopeTypes.REFLECTOR,
                magnification: '83X',
                observationRealDurationMin: 41,
                observationVirtualDurationMin: 41,
                observationStartDate: new Date('2022-02-12T19:02:00Z'),
                observationEndDate: new Date('2022-02-12T019:43:00Z'),
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString(),
              },
              {
                sessionId: 7,
                subject: 'Caldwell 14',
                telescopeType: telescopeTypes.REFLECTOR,
                magnification: '41X',
                observationRealDurationMin: 34,
                observationVirtualDurationMin: 33,
                observationStartDate: new Date('2022-03-13T03:04:00Z'),
                observationEndDate: new Date('2022-03-13T03:38:00Z'),
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString(),
              },
              {
                sessionId: 6,
                subject: 'M33',
                telescopeType: telescopeTypes.REFLECTOR,
                magnification: '139X',
                observationRealDurationMin: 32,
                observationVirtualDurationMin: 32,
                observationStartDate: new Date('2022-02-12T19:49:00Z'),
                observationEndDate: new Date('2022-02-12T20:21:00Z'),
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString(),
              },
            ],
            associations: {
              reports: {
                data: [
                  {
                    sessionId: 1,
                    subject: 'Moon',
                    telescopeType: telescopeTypes.REFLECTOR,
                    magnification: '83X',
                    observationRealDurationMin: 25,
                    observationVirtualDurationMin: 25,
                    observationStartDate: new Date('2022-02-12T23:24:00Z'),
                    observationEndDate: new Date('2022-02-12T23:49:00Z'),
                    createdAt: new Date().toISOString(),
                    updatedAt: new Date().toISOString(),
                  },
                  {
                    sessionId: 8,
                    subject: 'Jupiter',
                    telescopeType: telescopeTypes.REFLECTOR,
                    magnification: '139X',
                    observationRealDurationMin: 74,
                    observationVirtualDurationMin: 74,
                    observationStartDate: new Date('2022-03-09T17:49:00Z'),
                    observationEndDate: new Date('2022-03-09T19:03:00Z'),
                    createdAt: new Date().toISOString(),
                    updatedAt: new Date().toISOString(),
                  },
                  {
                    sessionId: 8,
                    subject: 'Saturn',
                    telescopeType: telescopeTypes.REFLECTOR,
                    magnification: '198',
                    observationRealDurationMin: 48,
                    observationVirtualDurationMin: 48,
                    observationStartDate: new Date('2022-03-09T19:10:00Z'),
                    observationEndDate: new Date('2022-03-09T19:58:00Z'),
                    createdAt: new Date().toISOString(),
                    updatedAt: new Date().toISOString(),
                  },
                  {
                    sessionId: 1,
                    subject: 'Moon',
                    telescopeType: telescopeTypes.REFLECTOR,
                    magnification: '250X',
                    observationRealDurationMin: 77,
                    observationVirtualDurationMin: 73,
                    observationStartDate: new Date('2022-02-12T23:53:00Z'),
                    observationEndDate: new Date('2022-03-13T01:06:00Z'),
                    createdAt: new Date().toISOString(),
                    updatedAt: new Date().toISOString(),
                  },
                  {
                    sessionId: 1,
                    subject: 'M44',
                    telescopeType: telescopeTypes.REFLECTOR,
                    magnification: '41X',
                    observationRealDurationMin: 51,
                    observationVirtualDurationMin: 51,
                    observationStartDate: new Date('2022-03-12T01:12:00Z'),
                    observationEndDate: new Date('2022-03-12T02:01:00Z'),
                    createdAt: new Date().toISOString(),
                    updatedAt: new Date().toISOString(),
                  },
                  {
                    sessionId: 5,
                    subject: 'Saturn',
                    telescopeType: telescopeTypes.CASSEGRAIN,
                    magnification: '220X',
                    observationRealDurationMin: 27,
                    observationVirtualDurationMin: 27,
                    observationStartDate: new Date('2022-03-01T17:41:00Z'),
                    observationEndDate: new Date('2022-03-01T18:08:00Z'),
                    createdAt: new Date().toISOString(),
                    updatedAt: new Date().toISOString(),
                  },
                  {
                    sessionId: 8,
                    subject: 'M44',
                    telescopeType: telescopeTypes.REFLECTOR,
                    magnification: '139X',
                    observationRealDurationMin: 33,
                    observationVirtualDurationMin: 31,
                    observationStartDate: new Date('2022-03-02T21:18:00Z'),
                    observationEndDate: new Date('2022-03-02T21:51:00Z'),
                    createdAt: new Date().toISOString(),
                    updatedAt: new Date().toISOString(),
                  },
                  {
                    sessionId: 9,
                    subject: 'Moon',
                    telescopeType: telescopeTypes.REFLECTOR,
                    magnification: '312X',
                    observationRealDurationMin: 120,
                    observationVirtualDurationMin: 120,
                    observationStartDate: new Date('2022-03-03T23:00:00Z'),
                    observationEndDate: new Date('2022-03-04T01:00:00Z'),
                    createdAt: new Date().toISOString(),
                    updatedAt: new Date().toISOString(),
                  },
                  {
                    sessionId: 8,
                    subject: 'M44',
                    telescopeType: telescopeTypes.REFLECTOR,
                    magnification: '41X',
                    observationRealDurationMin: 31,
                    observationVirtualDurationMin: 31,
                    observationStartDate: new Date('2022-03-02T21:52:00Z'),
                    observationEndDate: new Date('2022-03-02T22:23:00Z'),
                    createdAt: new Date().toISOString(),
                    updatedAt: new Date().toISOString(),
                  },
                  {
                    sessionId: 5,
                    subject: 'Saturn',
                    telescopeType: telescopeTypes.CASSEGRAIN,
                    magnification: '160X',
                    observationRealDurationMin: 47,
                    observationVirtualDurationMin: 39,
                    observationStartDate: new Date('2022-03-01T18:11:00Z'),
                    observationEndDate: new Date('2022-03-01T18:58:00Z'),
                    createdAt: new Date().toISOString(),
                    updatedAt: new Date().toISOString(),
                  },
                  {
                    sessionId: 3,
                    subject: 'M42',
                    telescopeType: telescopeTypes.REFLECTOR,
                    magnification: '225X',
                    observationRealDurationMin: 80,
                    observationVirtualDurationMin: 69,
                    observationStartDate: new Date('2022-02-16T20:00:00Z'),
                    observationEndDate: new Date('2022-02-16T21:20:00Z'),
                    createdAt: new Date().toISOString(),
                    updatedAt: new Date().toISOString(),
                  },
                  {
                    sessionId: 9,
                    subject: 'M44',
                    telescopeType: telescopeTypes.CASSEGRAIN,
                    magnification: '41X',
                    observationRealDurationMin: 45,
                    observationVirtualDurationMin: 43,
                    observationStartDate: new Date('2022-03-12T17:59:00Z'),
                    observationEndDate: new Date('2022-03-12T18:44:00Z'),
                    createdAt: new Date().toISOString(),
                    updatedAt: new Date().toISOString(),
                  },
                  {
                    sessionId: 9,
                    subject: 'Saturn',
                    telescopeType: telescopeTypes.CASSEGRAIN,
                    magnification: '280X',
                    observationRealDurationMin: 90,
                    observationVirtualDurationMin: 90,
                    observationStartDate: new Date('2022-03-12T22:00:00Z'),
                    observationEndDate: new Date('2022-03-12T23:30:00Z'),
                    createdAt: new Date().toISOString(),
                    updatedAt: new Date().toISOString(),
                  },
                  {
                    sessionId: 9,
                    subject: 'M51',
                    telescopeType: telescopeTypes.CASSEGRAIN,
                    magnification: '143X',
                    observationRealDurationMin: 120,
                    observationVirtualDurationMin: 120,
                    observationStartDate: new Date('2022-03-12T01:00:00Z'),
                    observationEndDate: new Date('2022-03-12T02:30:00Z'),
                    createdAt: new Date().toISOString(),
                    updatedAt: new Date().toISOString(),
                  },
                  {
                    sessionId: 9,
                    subject: 'NGC 457',
                    telescopeType: telescopeTypes.REFLECTOR,
                    magnification: '41X',
                    observationRealDurationMin: 13,
                    observationVirtualDurationMin: 13,
                    observationStartDate: new Date('2022-03-12T17:36:00Z'),
                    observationEndDate: new Date('2022-03-12T17:49:00Z'),
                    createdAt: new Date().toISOString(),
                    updatedAt: new Date().toISOString(),
                  },
                  {
                    sessionId: 2,
                    subject: 'Giades Open Cluster',
                    telescopeType: telescopeTypes.REFLECTOR,
                    magnification: '41X',
                    observationRealDurationMin: 37,
                    observationVirtualDurationMin: 37,
                    observationStartDate: new Date('2022-02-15T04:02:00Z'),
                    observationEndDate: new Date('2022-02-15T04:39:00Z'),
                    createdAt: new Date().toISOString(),
                    updatedAt: new Date().toISOString(),
                  },
                  {
                    sessionId: 2,
                    subject: 'M42',
                    telescopeType: telescopeTypes.REFLECTOR,
                    magnification: '83X',
                    observationRealDurationMin: 32,
                    observationVirtualDurationMin: 32,
                    observationStartDate: new Date('2022-02-15T00:09:00Z'),
                    observationEndDate: new Date('2022-02-15T00:41:00Z'),
                    createdAt: new Date().toISOString(),
                    updatedAt: new Date().toISOString(),
                  },
                  {
                    sessionId: 4,
                    subject: 'Caldwell 14',
                    telescopeType: telescopeTypes.REFLECTOR,
                    magnification: '83X',
                    observationRealDurationMin: 180,
                    observationVirtualDurationMin: 180,
                    observationStartDate: new Date('2022-12-23T02:00:00Z'),
                    observationEndDate: new Date('2022-12-23T05:00:00Z'),
                    createdAt: new Date().toISOString(),
                    updatedAt: new Date().toISOString(),
                  },
                  {
                    sessionId: 2,
                    subject: 'Giades Open Cluster',
                    telescopeType: telescopeTypes.REFLECTOR,
                    magnification: '83X',
                    observationRealDurationMin: 63,
                    observationVirtualDurationMin: 54,
                    observationStartDate: new Date('2022-02-18T01:58:00Z'),
                    observationEndDate: new Date('2022-02-18T03:01:00Z'),
                    createdAt: new Date().toISOString(),
                    updatedAt: new Date().toISOString(),
                  },
                  {
                    sessionId: 9,
                    subject: 'Caldwell 14',
                    telescopeType: telescopeTypes.CASSEGRAIN,
                    magnification: '41X',
                    observationRealDurationMin: 28,
                    observationVirtualDurationMin: 28,
                    observationStartDate: new Date('2022-03-12T05:14:00Z'),
                    observationEndDate: new Date('2022-03-12T05:42:00Z'),
                    createdAt: new Date().toISOString(),
                    updatedAt: new Date().toISOString(),
                  },
                  {
                    sessionId: 2,
                    subject: 'Caldwell 14',
                    telescopeType: telescopeTypes.REFLECTOR,
                    magnification: '41X',
                    observationRealDurationMin: 34,
                    observationVirtualDurationMin: 33,
                    observationStartDate: new Date('2022-02-18T03:04:00Z'),
                    observationEndDate: new Date('2022-02-18T03:38:00Z'),
                    createdAt: new Date().toISOString(),
                    updatedAt: new Date().toISOString(),
                  },
                  {
                    sessionId: 6,
                    subject: 'M33',
                    telescopeType: telescopeTypes.REFLECTOR,
                    magnification: '83X',
                    observationRealDurationMin: 41,
                    observationVirtualDurationMin: 41,
                    observationStartDate: new Date('2022-02-12T19:02:00Z'),
                    observationEndDate: new Date('2022-02-12T019:43:00Z'),
                    createdAt: new Date().toISOString(),
                    updatedAt: new Date().toISOString(),
                  },
                  {
                    sessionId: 7,
                    subject: 'Caldwell 14',
                    telescopeType: telescopeTypes.REFLECTOR,
                    magnification: '41X',
                    observationRealDurationMin: 34,
                    observationVirtualDurationMin: 33,
                    observationStartDate: new Date('2022-03-13T03:04:00Z'),
                    observationEndDate: new Date('2022-03-13T03:38:00Z'),
                    createdAt: new Date().toISOString(),
                    updatedAt: new Date().toISOString(),
                  },
                  {
                    sessionId: 6,
                    subject: 'M33',
                    telescopeType: telescopeTypes.REFLECTOR,
                    magnification: '139X',
                    observationRealDurationMin: 32,
                    observationVirtualDurationMin: 32,
                    observationStartDate: new Date('2022-02-12T19:49:00Z'),
                    observationEndDate: new Date('2022-02-12T20:21:00Z'),
                    createdAt: new Date().toISOString(),
                    updatedAt: new Date().toISOString(),
                  },
                ],
                associations: {
                  subjects: {
                    data: [
                      {
                        reportId: 1,
                        category: subjectTypes.MOON,
                        magnitude: -8.63,
                        apparentSize: 31.34,
                        semiMajorAxis: 4.76,
                        axialTilt: 3.44,
                        ecccentricity: 3.89,
                        inclination: 2.91,
                        rotation: 4.56,
                        createdAt: new Date().toISOString(),
                        updatedAt: new Date().toISOString(),
                      },
                      {
                        reportId: 2,
                        category: subjectTypes.PLANET,
                        magnitude: -3.95,
                        apparentSize: 12.46,
                        semiMajorAxis: 1.06,
                        axialTilt: 2.69,
                        ecccentricity: 8.76,
                        inclination: 2.91,
                        rotation: 2.32,
                        createdAt: new Date().toISOString(),
                        updatedAt: new Date().toISOString(),
                      },
                      {
                        reportId: 3,
                        category: subjectTypes.PLANET,
                        magnitude: -8.63,
                        apparentSize: 31.34,
                        semiMajorAxis: 0.0,
                        axialTilt: 3.44,
                        ecccentricity: 3.89,
                        inclination: 2.91,
                        rotation: 4.56,
                        createdAt: new Date().toISOString(),
                        updatedAt: new Date().toISOString(),
                      },
                      {
                        reportId: 4,
                        category: subjectTypes.MOON,
                        magnitude: -8.63,
                        apparentSize: 31.34,
                        semiMajorAxis: 4.76,
                        axialTilt: 3.44,
                        ecccentricity: 3.89,
                        inclination: 2.91,
                        rotation: 4.56,
                        createdAt: new Date().toISOString(),
                        updatedAt: new Date().toISOString(),
                      },
                      {
                        reportId: 5,
                        category: subjectTypes.OPEN_STAR_CLUSTER,
                        magnitude: 6.43,
                        createdAt: new Date().toISOString(),
                        updatedAt: new Date().toISOString(),
                      },
                      {
                        reportId: 6,
                        category: subjectTypes.PLANET,
                        magnitude: -8.63,
                        apparentSize: 31.34,
                        semiMajorAxis: 0.0,
                        axialTilt: 3.44,
                        ecccentricity: 3.89,
                        inclination: 2.91,
                        rotation: 4.56,
                        createdAt: new Date().toISOString(),
                        updatedAt: new Date().toISOString(),
                      },
                      {
                        reportId: 7,
                        category: subjectTypes.OPEN_STAR_CLUSTER,
                        magnitude: 6.43,
                        createdAt: new Date().toISOString(),
                        updatedAt: new Date().toISOString(),
                      },
                      {
                        reportId: 8,
                        category: subjectTypes.MOON,
                        magnitude: -7.79,
                        apparentSize: 29.01,
                        semiMajorAxis: 2.68,
                        axialTilt: 3.03,
                        ecccentricity: 4.02,
                        inclination: 2.81,
                        rotation: 4.88,
                        createdAt: new Date().toISOString(),
                        updatedAt: new Date().toISOString(),
                      },
                      {
                        reportId: 9,
                        category: subjectTypes.OPEN_STAR_CLUSTER,
                        magnitude: 6.43,
                        createdAt: new Date().toISOString(),
                        updatedAt: new Date().toISOString(),
                      },
                      {
                        reportId: 10,
                        category: subjectTypes.PLANET,
                        magnitude: -8.63,
                        apparentSize: 31.34,
                        semiMajorAxis: 0.0,
                        axialTilt: 3.44,
                        ecccentricity: 3.89,
                        inclination: 2.91,
                        rotation: 4.56,
                        createdAt: new Date().toISOString(),
                        updatedAt: new Date().toISOString(),
                      },
                      {
                        reportId: 11,
                        category: subjectTypes.NEBULA,
                        magnitude: 11.12,
                        createdAt: new Date().toISOString(),
                        updatedAt: new Date().toISOString(),
                      },
                      {
                        reportId: 12,
                        category: subjectTypes.OPEN_STAR_CLUSTER,
                        magnitude: 6.28,
                        createdAt: new Date().toISOString(),
                        updatedAt: new Date().toISOString(),
                      },
                      {
                        reportId: 13,
                        category: subjectTypes.PLANET,
                        magnitude: -8.63,
                        apparentSize: 31.34,
                        semiMajorAxis: 0.0,
                        axialTilt: 3.44,
                        ecccentricity: 3.89,
                        inclination: 2.91,
                        rotation: 4.56,
                        createdAt: new Date().toISOString(),
                        updatedAt: new Date().toISOString(),
                      },
                      {
                        reportId: 14,
                        category: subjectTypes.GALAXY,
                        magnitude: 11.94,
                        createdAt: new Date().toISOString(),
                        updatedAt: new Date().toISOString(),
                      },
                      {
                        reportId: 15,
                        category: subjectTypes.OPEN_STAR_CLUSTER,
                        magnitude: 6.28,
                        createdAt: new Date().toISOString(),
                        updatedAt: new Date().toISOString(),
                      },
                      {
                        reportId: 16,
                        category: subjectTypes.OPEN_STAR_CLUSTER,
                        magnitude: 8.84,
                        createdAt: new Date().toISOString(),
                        updatedAt: new Date().toISOString(),
                      },
                      {
                        reportId: 17,
                        category: subjectTypes.NEBULA,
                        magnitude: 9.31,
                        createdAt: new Date().toISOString(),
                        updatedAt: new Date().toISOString(),
                      },
                      {
                        reportId: 18,
                        category: subjectTypes.OPEN_STAR_CLUSTER,
                        magnitude: 8.84,
                        createdAt: new Date().toISOString(),
                        updatedAt: new Date().toISOString(),
                      },
                      {
                        reportId: 19,
                        category: subjectTypes.OPEN_STAR_CLUSTER,
                        magnitude: 7.04,
                        createdAt: new Date().toISOString(),
                        updatedAt: new Date().toISOString(),
                      },
                      {
                        reportId: 20,
                        category: subjectTypes.OPEN_STAR_CLUSTER,
                        magnitude: 8.84,
                        createdAt: new Date().toISOString(),
                        updatedAt: new Date().toISOString(),
                      },
                      {
                        reportId: 21,
                        category: subjectTypes.OPEN_STAR_CLUSTER,
                        magnitude: 7.04,
                        createdAt: new Date().toISOString(),
                        updatedAt: new Date().toISOString(),
                      },
                    ],
                  },
                },
              },
            },
          },
        },
      },
    },
  },
};
