'use strict';

module.exports = {
  up: async function (queryInterface) {
    await queryInterface.bulkInsert(
      'reports',
      [
        {
          sessionId: 1,
          subject: 'Moon',
          telescopeModel: 'Arsenal GSO DOB 10',
          magnification: '83X',
          observationRealDurationMin: 25,
          observationVirtualDurationMin: 25,
          observationStartDate: new Date('2022-02-12T23:24:00Z'),
          observationEndDate: new Date('2022-02-12T23:49:00Z'),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          sessionId: 1,
          subject: 'Jupiter',
          telescopeModel: 'Arsenal GSO DOB 10',
          magnification: '139X',
          observationRealDurationMin: 74,
          observationVirtualDurationMin: 74,
          observationStartDate: new Date('2022-02-12T23:49:00Z'),
          observationEndDate: new Date('2022-02-12T23:49:00Z'),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          sessionId: 1,
          subject: 'Moon',
          telescopeModel: 'Arsenal GSO DOB 10',
          magnification: '83X',
          observationRealDurationMin: 25,
          observationVirtualDurationMin: 25,
          observationStartDate: new Date('2022-02-12T23:24:00Z'),
          observationEndDate: new Date('2022-02-12T23:49:00Z'),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          sessionId: 1,
          subject: 'Jupiter',
          telescopeModel: 'Arsenal GSO DOB 10',
          magnification: '139X',
          observationRealDurationMin: 74,
          observationVirtualDurationMin: 74,
          observationStartDate: new Date('2022-02-12T23:49:00Z'),
          observationEndDate: new Date('2022-02-12T23:49:00Z'),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          sessionId: 2,
          subject: 'Saturn',
          telescopeModel: 'Arsenal GSO DOB 10',
          magnification: '198',
          observationRealDurationMin: 48,
          observationVirtualDurationMin: 48,
          observationStartDate: new Date('2022-02-12T23:24:00Z'),
          observationEndDate: new Date('2022-02-12T23:49:00Z'),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          sessionId: 2,
          subject: 'Moon',
          telescopeModel: 'Arsenal GSO DOB 10',
          magnification: '250X',
          observationRealDurationMin: 77,
          observationVirtualDurationMin: 73,
          observationStartDate: new Date('2022-02-12T23:24:00Z'),
          observationEndDate: new Date('2022-02-12T23:49:00Z'),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          sessionId: 2,
          subject: 'Moon',
          telescopeModel: 'Arsenal GSO DOB 10',
          magnification: '83X',
          observationRealDurationMin: 25,
          observationVirtualDurationMin: 25,
          observationStartDate: new Date('2022-02-12T23:24:00Z'),
          observationEndDate: new Date('2022-02-12T23:49:00Z'),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          sessionId: 2,
          subject: 'Jupiter',
          telescopeModel: 'Arsenal GSO DOB 10',
          magnification: '139X',
          observationRealDurationMin: 74,
          observationVirtualDurationMin: 74,
          observationStartDate: new Date('2022-02-12T23:49:00Z'),
          observationEndDate: new Date('2022-02-12T23:49:00Z'),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          sessionId: 3,
          subject: 'M44',
          telescopeModel: 'Arsenal GSO DOB 10',
          magnification: '41X',
          observationRealDurationMin: 51,
          observationVirtualDurationMin: 51,
          observationStartDate: new Date('2022-02-12T23:24:00Z'),
          observationEndDate: new Date('2022-02-12T23:49:00Z'),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          sessionId: 3,
          subject: 'Saturn',
          telescopeModel: 'Celestron CPC 1100 StarBright',
          magnification: '220X',
          observationRealDurationMin: 27,
          observationVirtualDurationMin: 27,
          observationStartDate: new Date('2022-02-12T23:24:00Z'),
          observationEndDate: new Date('2022-02-12T23:49:00Z'),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          sessionId: 3,
          subject: 'Moon',
          telescopeModel: 'Arsenal GSO DOB 10',
          magnification: '83X',
          observationRealDurationMin: 25,
          observationVirtualDurationMin: 25,
          observationStartDate: new Date('2022-02-12T23:24:00Z'),
          observationEndDate: new Date('2022-02-12T23:49:00Z'),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          sessionId: 3,
          subject: 'Jupiter',
          telescopeModel: 'Arsenal GSO DOB 10',
          magnification: '139X',
          observationRealDurationMin: 74,
          observationVirtualDurationMin: 74,
          observationStartDate: new Date('2022-02-12T23:49:00Z'),
          observationEndDate: new Date('2022-02-12T23:49:00Z'),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {
        timestamps: true,
      }
    );
  },

  down: async function (queryInterface) {
    await queryInterface.bulkDelete('reports', null, {});
  },
};
