'use strict';

// eslint-disable-next-line @typescript-eslint/no-var-requires
const { subjectTypes } = require('../consts');

module.exports = {
  up: async function (queryInterface) {
    await queryInterface.bulkInsert(
      'subjects',
      [
        {
          reportId: 1,
          category: subjectTypes.MOON,
          magnitude: -8.63,
          apparentSize: 31.34,
          semiMajorAxis: 4.76,
          axialTilt: 3.44,
          ecccentricity: 3.89,
          inclination: 2.91,
          rotation: 4.56,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          reportId: 2,
          category: subjectTypes.PLANET,
          magnitude: -3.95,
          apparentSize: 12.46,
          semiMajorAxis: 1.06,
          axialTilt: 2.69,
          ecccentricity: 8.76,
          inclination: 2.91,
          rotation: 2.32,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          reportId: 3,
          category: subjectTypes.PLANET,
          magnitude: -8.63,
          apparentSize: 31.34,
          semiMajorAxis: 0.0,
          axialTilt: 3.44,
          ecccentricity: 3.89,
          inclination: 2.91,
          rotation: 4.56,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          reportId: 4,
          category: subjectTypes.MOON,
          magnitude: -8.63,
          apparentSize: 31.34,
          semiMajorAxis: 4.76,
          axialTilt: 3.44,
          ecccentricity: 3.89,
          inclination: 2.91,
          rotation: 4.56,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          reportId: 5,
          category: subjectTypes.OPEN_STAR_CLUSTER,
          magnitude: 6.43,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          reportId: 6,
          category: subjectTypes.PLANET,
          magnitude: -8.63,
          apparentSize: 31.34,
          semiMajorAxis: 0.0,
          axialTilt: 3.44,
          ecccentricity: 3.89,
          inclination: 2.91,
          rotation: 4.56,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          reportId: 7,
          category: subjectTypes.OPEN_STAR_CLUSTER,
          magnitude: 6.43,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          reportId: 8,
          category: subjectTypes.MOON,
          magnitude: -7.79,
          apparentSize: 29.01,
          semiMajorAxis: 2.68,
          axialTilt: 3.03,
          ecccentricity: 4.02,
          inclination: 2.81,
          rotation: 4.88,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          reportId: 9,
          category: subjectTypes.OPEN_STAR_CLUSTER,
          magnitude: 6.43,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          reportId: 10,
          category: subjectTypes.PLANET,
          magnitude: -8.63,
          apparentSize: 31.34,
          semiMajorAxis: 0.0,
          axialTilt: 3.44,
          ecccentricity: 3.89,
          inclination: 2.91,
          rotation: 4.56,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          reportId: 11,
          category: subjectTypes.NEBULA,
          magnitude: 11.12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          reportId: 12,
          category: subjectTypes.OPEN_STAR_CLUSTER,
          magnitude: 6.28,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          reportId: 13,
          category: subjectTypes.PLANET,
          magnitude: -8.63,
          apparentSize: 31.34,
          semiMajorAxis: 0.0,
          axialTilt: 3.44,
          ecccentricity: 3.89,
          inclination: 2.91,
          rotation: 4.56,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          reportId: 14,
          category: subjectTypes.GALAXY,
          magnitude: 11.94,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          reportId: 15,
          category: subjectTypes.OPEN_STAR_CLUSTER,
          magnitude: 6.28,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          reportId: 16,
          category: subjectTypes.OPEN_STAR_CLUSTER,
          magnitude: 8.84,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          reportId: 17,
          category: subjectTypes.NEBULA,
          magnitude: 9.31,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          reportId: 18,
          category: subjectTypes.OPEN_STAR_CLUSTER,
          magnitude: 8.84,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          reportId: 19,
          category: subjectTypes.OPEN_STAR_CLUSTER,
          magnitude: 7.04,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          reportId: 20,
          category: subjectTypes.OPEN_STAR_CLUSTER,
          magnitude: 8.84,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          reportId: 21,
          category: subjectTypes.OPEN_STAR_CLUSTER,
          magnitude: 7.04,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          reportId: 22,
          category: subjectTypes.GALAXY,
          magnitude: 11.94,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          reportId: 23,
          category: subjectTypes.OPEN_STAR_CLUSTER,
          magnitude: 7.04,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          reportId: 24,
          category: subjectTypes.GALAXY,
          magnitude: 11.94,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {
        timestamps: true,
      }
    );
  },

  down: async function (queryInterface) {
    await queryInterface.bulkDelete('subjects', null, {});
  },
};
