'use strict';

// eslint-disable-next-line @typescript-eslint/no-var-requires
const { subjectTypes } = require('../consts');

module.exports = {
  up: async function (queryInterface) {
    await queryInterface.bulkInsert(
      'subjects',
      [
        {
          reportId: 1,
          category: subjectTypes.MOON,
          magnitude: -8.63,
          rightAscendance: '8h 26.3m',
          declination: "+19deg 04'",
          apparentSize: 31.34,
          semiMajorAxis: 4.76,
          axialTilt: 3.44,
          ecccentricity: 3.89,
          orbitalInclination: 2.91,
          rotation: 4.56,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          reportId: 2,
          category: subjectTypes.PLANET,
          magnitude: -3.95,
          rightAscendance: '6h 11.8m',
          declination: "-4deg 06'",
          apparentSize: 12.46,
          semiMajorAxis: 1.06,
          axialTilt: 2.69,
          ecccentricity: 8.76,
          orbitalInclination: 2.91,
          rotation: 2.32,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          reportId: 3,
          category: subjectTypes.PLANET,
          magnitude: -8.63,
          rightAscendance: '5h 42.1m',
          declination: "-9deg 13'",
          apparentSize: 31.34,
          semiMajorAxis: 0.0,
          axialTilt: 3.44,
          ecccentricity: 3.89,
          orbitalInclination: 2.91,
          rotation: 4.56,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          reportId: 4,
          category: subjectTypes.MOON,
          magnitude: -8.63,
          rightAscendance: '8h 26.3m',
          declination: "+19deg 04'",
          apparentSize: 31.34,
          semiMajorAxis: 4.76,
          axialTilt: 3.44,
          ecccentricity: 3.89,
          orbitalInclination: 2.91,
          rotation: 4.56,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          reportId: 5,
          category: subjectTypes.OPEN_STAR_CLUSTER,
          magnitude: 6.43,
          rightAscendance: '20h 23.9m',
          declination: "+38deg 32'",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          reportId: 6,
          category: subjectTypes.PLANET,
          magnitude: -8.63,
          rightAscendance: '5h 42.1m',
          declination: "-9deg 13'",
          apparentSize: 31.34,
          semiMajorAxis: 0.0,
          axialTilt: 3.44,
          ecccentricity: 3.89,
          orbitalInclination: 2.91,
          rotation: 4.56,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          reportId: 7,
          category: subjectTypes.MOON,
          magnitude: -8.63,
          rightAscendance: '8h 26.3m',
          declination: "+19deg 04'",
          apparentSize: 31.34,
          semiMajorAxis: 4.76,
          axialTilt: 3.44,
          ecccentricity: 3.89,
          orbitalInclination: 2.91,
          rotation: 4.56,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          reportId: 8,
          category: subjectTypes.PLANET,
          magnitude: -3.95,
          rightAscendance: '6h 11.8m',
          declination: "-4deg 06'",
          apparentSize: 12.46,
          semiMajorAxis: 1.06,
          axialTilt: 2.69,
          ecccentricity: 8.76,
          orbitalInclination: 2.91,
          rotation: 2.32,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          reportId: 9,
          category: subjectTypes.PLANET,
          magnitude: -8.63,
          rightAscendance: '5h 42.1m',
          declination: "-9deg 13'",
          apparentSize: 31.34,
          semiMajorAxis: 0.0,
          axialTilt: 3.44,
          ecccentricity: 3.89,
          orbitalInclination: 2.91,
          rotation: 4.56,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          reportId: 10,
          category: subjectTypes.MOON,
          magnitude: -8.63,
          rightAscendance: '8h 26.3m',
          declination: "+19deg 04'",
          apparentSize: 31.34,
          semiMajorAxis: 4.76,
          axialTilt: 3.44,
          ecccentricity: 3.89,
          orbitalInclination: 2.91,
          rotation: 4.56,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          reportId: 11,
          category: subjectTypes.OPEN_STAR_CLUSTER,
          magnitude: 6.43,
          rightAscendance: '20h 23.9m',
          declination: "+38deg 32'",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          reportId: 12,
          category: subjectTypes.PLANET,
          magnitude: -8.63,
          rightAscendance: '5h 42.1m',
          declination: "-9deg 13'",
          apparentSize: 31.34,
          semiMajorAxis: 0.0,
          axialTilt: 3.44,
          ecccentricity: 3.89,
          orbitalInclination: 2.91,
          rotation: 4.56,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {
        timestamps: true,
      }
    );
  },

  down: async function (queryInterface) {
    await queryInterface.bulkDelete('subjects', null, {});
  },
};
