'use strict';

export async function up(queryInterface) {
  await queryInterface.bulkInsert('user_tokens', [
    {
      userId: 1,
      refreshToken: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eymaWNhdGlvbkxpbmsiOiIiLCJpZCI6JkYXRhVmFsdWVzIjp7ImlzVmVyaWZpZWQiOjAsInZlcmlMywidXNlcm5hbWUiOiJucGFuY2gyOTg5IiwiZW1haWwiOiJuYXphci5wYW5jaGVua29AaW5jb2RlLWl0LmNvbSIsInBhc3N3b3JkIjoiJDJiJDE1JGpKV0JpQ3FHek5leTJteERZT2FHVXVCbERta0VRT0VPYU1HMUJQWFNRVTBQQklJMXpWYks2IiwidXBkYXRlZEF0IjoiMjAyMy0wMy0xM1QyMjowODozNC44OTZaIiwiY3JlYXRlZEF0IjoiMjAyMy0wMy0xM1QyMjowODozNC44OTZaIn0sIl9wcmV2aW91c0RhdGFWYWx1ZXMiOnsidXNlcm5hbWUiOiJucGFuY2gyOTg5IiwiZW1haWwiOiJuYXphci5wYW5jaGVua29AaW5jb2RlLWl0LmNvbSIsInBhc3N3b3JkIjoiJDJiJDE1JGpKV0JpQ3FHek5leTJteERZT2FHVXVCbERta0VRT0VPYU1HMUJQWFNRVTBQQklJMXpWYks2IiwiaWQiOjMsImlzVmVyaWZpZWQiOjAsInZlcmlmaWNhdGlvbkxpbmsiOiIiLCJjcmVhdGVkQXQiOiIyMDIzLTAzLTEzVDIyOjA4OjM0Ljg5NloiLCJ1cGRhdGVkQXQiOiIyMDIzLTAzLTEzVDIyOjA4OjM0Ljg5NloifSwidW5pcW5vIjoxLCJfY2hhbmdlZCI6e30sIl9vcHRpb25zIjp7ImlzTmV3UmVjb3JkIjp0cnVlLCJfc2NoZW1hIjpudWxsLCJfc2NoZW1hRGVsaW1pdGVyIjoiIn0sImlzTmV3UmVjb3JkIjpmYWxzZSwiaWF0IjoxNjc4NzQ1MzE3LCJleHAiOjE2Nzg3NDU2Nzd9.JU5iGC7nrKno2lF5ueCiho350W7NQ7zD6yzuQT8pEwM',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      userId: 2,
      refreshToken: '9JCVXPKi6cInIsI1ZUJiOgcHbaYe.eyJpZCI6MywidXNlcm5hbWkYXRhVmFsdWVzIjp7ImlzVmVyaWZpZWQiOjAsInZlcmlmaWNhdGlvbkxpbmsiOiIiLCJUiOiJucGFuY2gyOTg5IiwiZW1haWwiOiJuYXphci5wYW5jaGVua29AaW5jb2RlLWl0LmNvbSIsInBhc3N3b3JkIjoiJDJiJDE1JGpKV0JpQ3FHek5leTJteERZT2FHVXVCbERta0VRT0VPYU1HMUJQWFNRVTBQQklJMXpWYks2IiwidXBkYXRlZEF0IjoiMjAyMy0wMy0xM1QyMjowODozNC44OTZaIiwiY3JlYXRlZEF0IjoiMjAyMy0wMy0xM1QyMjowODozNC44OTZaIn0sIl9wcmV2aW91c0RhdGFWYWx1ZXMiOnsidXNlcm5hbWUiOiJucGFuY2gyOTg5IiwiZW1haWwiOiJuYXphci5wYW5jaGVua29AaW5jb2RlLWl0LmNvbSIsInBhc3N3b3JkIjoiJDJiJDE1JGpKV0JpQ3FHek5leTJteERZT2FHVXVCbERta0VRT0VPYU1HMUJQWFNRVTBQQklJMXpWYks2IiwiaWQiOjMsImlzVmVyaWZpZWQiOjAsInZlcmlmaWNhdGlvbkxpbmsiOiIiLCJjcmVhdGVkQXQiOiIyMDIzLTAzLTEzVDIyOjA4OjM0Ljg5NloiLCJ1cGRhdGVkQXQiOiIyMDIzLTAzLTEzVDIyOjA4OjM0Ljg5NloifSwidW5pcW5vIjoxLCJfY2hhbmdlZCI6e30sIl9vcHRpb25zIjp7ImlzTmV3UmVjb3JkIjp0cnVlLCJfc2NoZW1hIjpudWxsLCJfc2NoZW1hRGVsaW1pdGVyIjoiIn0sImlzTmV3UmVjb3JkIjpmYWxzZSwiaWF0IjoxNjc4NzQ1MzE3LCJleHAiOjE2Nzg3NDU2Nzd9.JU5iGC7nrKno2lF5ueCiho350W7NQ7zD6yzuQT8pEwM',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      userId: 3,
      refreshToken: 'IsInR5cCI6IkpXVCJ9eyJhbGciOiJIUzI1Ni.eyJkYXRhVmFsdWVzIjp7ImlzVmVyaWZpZWQiOjAsInZlcmlmaWNhdGlvbkxpbmsiOiIiLCJpZCI6MywidXNlcm5hbWUiOiJucGFuY2gyOTg5IiwiZW1haWwiOiJuYXphci5wYW5jaGVua29AaW5jb2RlLWl0LmNvbSIsInBhc3N3b3JkIjoiJDJiJDE1JGpKV0JpQ3FHek5leTJteERZT2FHVXVCbERta0VRT0VPYU1HMUJQWFNRVTBQQklJMXpWYks2IiwidXBkYXRlZEF0IjoiMjAyMy0wMy0xM1QyMjowODozNC44OTZaIiwiY3JlYXRlZEF0IjoiMjAyMy0wMy0xM1QyMjowODozNC44OTZaIn0sIl9wcmV2aW91c0RhdGFWYWx1ZXMiOnsidXNlcm5hbWUiOiJucGFuY2gyOTg5IiwiZW1haWwiOiJuYXphci5wYW5jaGVua29AaW5jb2RlLWl0LmNvbSIsInBhc3N3b3JkIjoiJDJiJDE1JGpKV0JpQ3FHek5leTJteERZT2FHVXVCbERta0VRT0VPYU1HMUJQWFNRVTBQQklJMXpWYks2IiwiaWQiOjMsImlzVmVyaWZpZWQiOjAsInZlcmlmaWNhdGlvbkxpbmsiOiIiLCJjcmVhdGVkQXQiOiIyMDIzLTAzLTEzVDIyOjA4OjM0Ljg5NloiLCJ1cGRhdGVkQXQiOiIyMDIzLTAzLTEzVDIyOjA4OjM0Ljg5NloifSwidW5pcW5vIjoxLCJfY2hhbmdlZCI6e30sIl9vcHRpb25zIjp7ImlzTmV3UmVjb3JkIjp0cnVlLCJfc2NoZW1hIjpudWxsLCJfc2NoZW1hRGVsaW1pdGVyIjoiIn0sImlzTmV3UmVjb3JkIjpmYWxzZSwiaWF0IjoxNjc4NzQ1MzE3LCJleHAiOjE2Nzg3NDU2Nzd9.JU5iGC7nrKno2lF5ueCiho350W7NQ7zD6yzuQT8pEwM',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ]);
}

export async function down(queryInterface) {
  await queryInterface.bulkDelete('user_tokens', null, {});
}
